In [13]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
transposed_array = array.T  
print("Original Array:\n", array)
print("Transposed Array:\n", transposed_array)


Original Array:
 [[ 1  2 71]
 [48 83 21]
 [97 70 93]]
Transposed Array:
 [[ 1 48 97]
 [ 2 83 70]
 [71 21 93]]


In [15]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
array = np.arange(10)  
reshaped_2x5 = array.reshape(2, 5)
reshaped_5x2 = array.reshape(5, 2)
print("2x5 Array:\n", reshaped_2x5)
print("5x2 Array:\n", reshaped_5x2)


2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
array = np.random.rand(4, 4) 
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Bordered Array:\n", bordered_array)


Bordered Array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.59412951 0.03597446 0.61450771 0.85398818 0.        ]
 [0.         0.16901431 0.96142804 0.37733375 0.24877084 0.        ]
 [0.         0.438382   0.6178702  0.28678208 0.93519874 0.        ]
 [0.         0.34885731 0.15345041 0.0985494  0.41887846 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [19]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
array = np.arange(10, 61, 5)
print("Array with Step of 5:\n", array)


Array with Step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [21]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
array = np.array(['python', 'numpy', 'pandas'])
uppercase = np.char.upper(array)
lowercase = np.char.lower(array)
titlecase = np.char.title(array)
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [23]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
words = np.array(['hello', 'world'])
spaced_words = np.char.join(" ", words)
print("Spaced Words:", spaced_words)


Spaced Words: ['h e l l o' 'w o r l d']


In [25]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [29]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import sympy 
array = np.random.randint(0, 1000, size=100)
primes = [num for num in array if sympy.isprime(num)]
print("Prime Numbers:", primes)


Prime Numbers: [233, 137, 397, 971, 659, 491, 421, 557, 787, 103, 277, 251, 743, 617, 43, 653, 389, 13, 109, 547, 773, 491, 491, 389]


In [31]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
temperatures = np.random.randint(20, 40, size=30)  
weekly_averages = [np.mean(temperatures[i:i+7]) for i in range(0, 30, 7)]
print("Weekly Averages:", weekly_averages)


Weekly Averages: [26.571428571428573, 26.857142857142858, 30.428571428571427, 29.857142857142858, 24.5]
